IF NOT EXISTS(SELECT * FROM SYS.tables WHERE name = 'Mbl_CMN_RefreshTokenDtls')
BEGIN
	CREATE TABLE Mbl_CMN_RefreshTokenDtls
	(
		Id INT IDENTITY PRIMARY KEY,
		UserId INT NOT NULL,
		Token NVARCHAR(200) NOT NULL,
		Expires DATETIME NOT NULL,
		Created DATETIME NOT NULL DEFAULT GETDATE(),
		Revoked DATETIME NULL
	 )
END